[package]
name = "anylive-social"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anylive-common = { path = "../common" }
anylive-domain = { path = "../domain" }
tokio = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
