[package]
name = "anylive-db"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anylive-auth = { path = "../auth" }
anylive-common = { path = "../common" }
anylive-domain = { path = "../domain" }
anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
