[package]
name = "anylive-auth"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anylive-common = { path = "../common" }
anylive-domain = { path = "../domain" }
async-trait = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
jsonwebtoken = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
reqwest = { workspace = true }
argon2 = { workspace = true }
password-hash = { workspace = true }
rand_core = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
