#!/usr/bin/env bash
# Generate TypeScript types from contracts/openapi/openapi.yaml (WBS E1.5 scaffold).
#
# Uses openapi-typescript (no Vue Query / Orval runtime). Orval can replace this
# later for full client+hooks; types-only keeps the monorepo lean.
#
# Usage:
#   ./scripts/gen-openapi-ts.sh
#   CHECK=1 ./scripts/gen-openapi-ts.sh   # fail if working tree would change
#
# Outputs:
#   apps/admin-web/src/generated/openapi.d.ts
#   apps/h5-web/src/generated/openapi.d.ts

set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SPEC="$ROOT/contracts/openapi/openapi.yaml"
OUT_ADMIN="$ROOT/apps/admin-web/src/generated/openapi.d.ts"
OUT_H5="$ROOT/apps/h5-web/src/generated/openapi.d.ts"

if [[ ! -f "$SPEC" ]]; then
  echo "missing $SPEC" >&2
  exit 1
fi

gen_one() {
  local out="$1"
  mkdir -p "$(dirname "$out")"
  # Prefer local npx; pin major for reproducibility.
  npx --yes openapi-typescript@7.4.4 "$SPEC" -o "$out"
  # Header so reviewers know source of truth.
  local tmp
  tmp="$(mktemp)"
  {
    echo "// GENERATED by scripts/gen-openapi-ts.sh — do not edit."
    echo "// Source: contracts/openapi/openapi.yaml"
    cat "$out"
  } >"$tmp"
  mv "$tmp" "$out"
  echo "wrote $out"
}

gen_one "$OUT_ADMIN"
# Same types for H5 (shared contract); copy to avoid dual npx cost.
mkdir -p "$(dirname "$OUT_H5")"
cp "$OUT_ADMIN" "$OUT_H5"
echo "wrote $OUT_H5"

if [[ "${CHECK:-0}" == "1" ]]; then
  if ! git -C "$ROOT" diff --quiet -- \
    apps/admin-web/src/generated/openapi.d.ts \
    apps/h5-web/src/generated/openapi.d.ts; then
    echo "FAIL: generated OpenAPI types are stale. Run ./scripts/gen-openapi-ts.sh" >&2
    git -C "$ROOT" --no-pager diff --stat -- \
      apps/admin-web/src/generated/openapi.d.ts \
      apps/h5-web/src/generated/openapi.d.ts || true
    exit 1
  fi
  echo "openapi ts check: ok"
fi
